export const GET_FAVOURITE_ARTISTS = 'GET_FAVOURITE_ARTISTS';
export const STORE_FAVOURITE_ARTISTS = 'STORE_FAVOURITE_ARTISTS';
export const FETCH_FAVOURITE_ARTISTS = 'FETCH_FAVOURITE_ARTISTS';
export const FETCH_FAVOURITE_ARTISTS_FAILED = 'FETCH_FAVOURITE_ARTISTS_FAILED';


