// Artists
export const FETCH_FAVOURITE_ARTISTS = 'FETCH_FAVOURITE_ARTISTS';
export const FETCH_FAVOURITE_ARTISTS_FAILED = 'FETCH_FAVOURITE_ARTISTS_FAILED';
export const STORE_FAVOURITE_ARTISTS = 'STORE_FAVOURITE_ARTISTS';
export const FETCH_ARTIST_INFO = 'FETCH_ARTIST_INFO';
export const FETCH_ARTIST_INFO_FAILED = 'FETCH_ARTIST_INFO_FAILED';
export const STORE_CURRENT_ARTIST = 'STORE_CURRENT_ARTIST';

// Albums
export const FETCH_FAVOURITE_ALBUMS = 'FETCH_FAVOURITE_ALBUMS';
export const FETCH_FAVOURITE_ALBUMS_FAILED = 'FETCH_FAVOURITE_ALBUMS_FAILED';
export const STORE_FAVOURITE_ALBUMS = 'STORE_FAVOURITE_ALBUMS';
export const FETCH_ALBUM_INFO = 'FETCH_ALBUM_INFO';
export const FETCH_ALBUM_INFO_FAILED = 'FETCH_ALBUM_INFO_FAILED';
export const STORE_CURRENT_ALBUM = 'STORE_CURRENT_ALBUM';


// Tracks
export const STORE_FAVOURITE_TRACKS = 'STORE_FAVOURITE_TRACKS';
export const FETCH_FAVOURITE_TRACKS = 'FETCH_FAVOURITE_TRACKS';
export const FETCH_FAVOURITE_TRACKS_FAILED = 'FETCH_FAVOURITE_TRACKS_FAILED';

// User
export const STORE_LOGGED_USER = 'STORE_LOGGED_USER';
export const FETCH_LOGGED_USER = 'FETCH_LOGGED_USER';
export const FETCH_LOGGED_USER_FAILED = 'FETCH_LOGGED_USER_FAILED';
export const SET_LOGGED_USER = 'SET_LOGGED_USER';
